name: dtubeapp
description: Stream Dube content.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  font_awesome_flutter: ^8.8.1
  dio: ^3.0.10
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.8
  screen: ^0.0.5
  html: ^0.14.0+3
  uni_links: ^0.4.0
  flutter_custom_tabs: ^0.6.0
  firebase_admob: ^0.9.0+10
  firebase_analytics: ^6.0.0
  video_player: ^0.10.11+2
  flutter_billing: ^0.4.0
  package_info: ^0.4.1
  share: ^0.6.4+3
  flutter_android_pip: ^0.0.2
  flutter_local_notifications: ^1.4.4+3
  permission_handler: ^5.0.1+1
  open_file: ^3.0.1
  flutter_downloader: ^1.5.0
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.2.1
  simple_moment: ^1.0.6
  cupertino_icons: ^0.1.3
  #video_launcher: ^0.2.0
  #flutter_html_view: ^0.5.12
  flutter_html: ^1.0.0
  chewie: ^0.9.10

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/video_placeholder.png
   - assets/web_hi_res_512.png
   - assets/DTube_Black.png
   - assets/DTube_White.png
   - "assets/screenshot (1).jpg"
   - "assets/screenshot (2).jpg"
   - "assets/screenshot (3).jpg"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
